/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_panorama_NativePanorama */

#ifndef _Included_example_motion_NativePanorama
#define _Included_example_motion_NativePanorama
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jlong JNICALL Java_org_iii_snsi_videotracking_NativeCamshift_initialize
  (JNIEnv *env, jclass clazz);

JNIEXPORT jint JNICALL Java_org_iii_snsi_videotracking_NativeCamshift_initCamshiftA
  (JNIEnv *env, jclass clazz, jlong handle, jbyteArray image, jint width,
  jint height, jintArray rect);

JNIEXPORT jint JNICALL Java_org_iii_snsi_videotracking_NativeCamshift_initCamshiftO
  (JNIEnv *env, jclass clazz, jlong handle, jbyteArray image, jint width,
   jint height, jobject rect);

JNIEXPORT jboolean JNICALL Java_org_iii_snsi_videotracking_NativeCamshift_processCamshiftA
  (JNIEnv *env, jclass clazz, jlong handle, jbyteArray image, jint width,
   jint height, jintArray rects);

JNIEXPORT jboolean JNICALL Java_org_iii_snsi_videotracking_NativeCamshift_processCamshiftO
  (JNIEnv *env, jclass clazz, jlong handle, jbyteArray image, jint width,
   jint height, jobject rects);

JNIEXPORT void JNICALL Java_org_iii_snsi_videotracking_NativeCamshift_deleteRectangle
  (JNIEnv *env, jclass clazz, jlong handle, jint id);

JNIEXPORT void JNICALL Java_org_iii_snsi_videotracking_NativeCamshift_releaseHandle
  (JNIEnv *env, jclass clazz, jlong handle);

#ifdef __cplusplus
}
#endif
#endif
