/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iii_snsi_videotracking_NativeTracking */

#ifndef _Included_org_iii_snsi_videotracking_NativeTracking
#define _Included_org_iii_snsi_videotracking_NativeTracking
#ifdef __cplusplus
extern "C" {
#endif
    JNIEXPORT jlong JNICALL Java_org_iii_snsi_videotracking_NativeTracking_createHandle
    (JNIEnv *env, jclass clazz);

    JNIEXPORT jint JNICALL Java_org_iii_snsi_videotracking_NativeTracking_initTrackingA
    (JNIEnv *env, jclass clazz, jlong handle, jbyteArray image, jint width,
            jint height, jintArray rect);

    JNIEXPORT jint JNICALL Java_org_iii_snsi_videotracking_NativeTracking_initTrackingO
    (JNIEnv *env, jclass clazz, jlong handle, jbyteArray image, jint width,
            jint height, jobjectArray rects);

    JNIEXPORT jint JNICALL Java_org_iii_snsi_videotracking_NativeTracking_addTrackingObjectA
    (JNIEnv *env, jclass clazz, jlong handle, jbyteArray image, jintArray rect);

    JNIEXPORT jint JNICALL Java_org_iii_snsi_videotracking_NativeTracking_addTrackingObjectO
    (JNIEnv *env, jclass clazz, jlong handle, jbyteArray image, jobject rect);

    JNIEXPORT void JNICALL Java_org_iii_snsi_videotracking_NativeTracking_removeTrackingObject
    (JNIEnv *env, jclass clazz, jlong handle, jint id);

    JNIEXPORT jboolean JNICALL Java_org_iii_snsi_videotracking_NativeTracking_processTrackingA
    (JNIEnv *env, jclass clazz, jlong handle, jbyteArray image,
            jintArray rects);

    JNIEXPORT jboolean JNICALL Java_org_iii_snsi_videotracking_NativeTracking_processTrackingO
    (JNIEnv *env, jclass clazz, jlong handle, jbyteArray image, jobject rects);

    JNIEXPORT void JNICALL Java_org_iii_snsi_videotracking_NativeTracking_releaseHandle
    (JNIEnv *env, jclass clazz, jlong handle);

#ifdef __cplusplus
}
#endif
#endif
